---
- name: Download Magento Downloader
  get_url: url=http://www.magentocommerce.com/downloads/assets/{{ mag_version }}/magento-{{ mag_version }}.tar.gz dest=/var/www/magento-{{ mag_version }}.tar.gz

- name: Extract Archive
  command: chdir=/var/www/ /bin/tar xvf magento-{{ mag_version }}.tar.gz

- name: Change Magento folder to Domain name
  shell: chdir=/var/www/ mv magento {{ domain_name }}

- name: Add group "nginx"
  group: name=nginx

- name: Change ownership of Magento installation
  file: path=/var/www/{{ domain_name }}/ owner=nginx group=nginx state=directory recurse=yes

- name: Change ownership of magento installation 2
  shell: chdir=/var/www/{{ domain_name }}/ find . -type f -exec chmod 644 {} \;

- name: Change ownership of magento installation 3
  shell: chdir=/var/www/{{ domain_name }}/ find . -type d -exec chmod 755 {} \;

- name: Change ownership of magento installation 4
  shell: chdir=/var/www/{{ domain_name }}/ chmod o+w var var/.htaccess app/etc

- name: Change ownership of magento installation 5
  shell: chdir=/var/www/{{ domain_name }}/ chmod 550 mage

- name: Change ownership of magento installation 6
  shell: chdir=/var/www/{{ domain_name }}/ chmod -R o+w media

- name: Create Magento database
  mysql_db: name={{ mag_db_name }} state=present

- name: Create Magento database user
  mysql_user: name={{ mag_db_user }} password={{ mag_db_password }} priv={{ mag_db_name }}.*:ALL host='localhost' state=present

- name: Mage Setup
  shell: chdir=/var/www/{{ domain_name }}/ ./mage mage-setup .
  
- name: Mage Stable State
  shell: chdir=/var/www/{{ domain_name }}/ ./mage config-set preferred_state stable

- name: Install Core
  shell: chdir=/var/www/{{ domain_name }}/ ./mage install http://connect20.magentocommerce.com/community Mage_All_Latest --force
